[package]
name = "latte-primitives"
version = "0.1.0"
edition = "2024"

[dependencies]
sha2 = "0.10"
blake3 = "1.5"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
thiserror = "2.0.17"
serde = { version = "1", features = ["derive"] }