[package]
name = "latte-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
latte-primitives = { path = "../primitives" }
latte-types = { path = "../types" }
latte-state = { path = "../state" }
thiserror = "1"
bincode = "1.3.3"